### ISSUE TITLE
ЭНЕРГИЯ

### ISSUE THREAD

**Issue by AlgorithmLX** [Domaman202/DmNTech#3]
Слухай, используй встроенную в FABRIС энергию

**Comment by AlgorithmLX** [comment]
![image](https://user-images.githubusercontent.com/46783751/138554892-a3944829-4092-4b39-b155-74ebce6d997b.png)

**Comment by Domaman202** [comment]
> Слухай, используй встроенную в FABRIС энергию

где я её тебе высру?

**Comment by AlgorithmLX** [comment]
https://github.com/TechReborn/Energy НА-А

**Comment by Domaman202** [comment]
всё хуйня
хочу свою.

**Comment by AlgorithmLX** [comment]
Ну.. Удачи ебаться
